a) Write a code taking as input a matrix A of size m× n and a vector b
of size m×1, where m and n are arbitrarily large numbers and m < n,
constructing the augmented matrix and performing
ˆ REF, and
ˆ RREF
without using any built-in functions. In case you encounter any division
by 0, you can choose a different A and/or b.
Deliverables: The code snippet showing the procedure for REF and
RREF. (1 mark + 1 mark)

In [200]:
import numpy as np
import random
import copy
print("Enter value of m and n for creating m X n matrix : NOTE m < n")
#m=int(input("m"))
#n=int(input("n"))

m=3
n=5

#A = np.random.randint(10, size=(m,n)) 
#b = np.random.randint(10, size=(m))

#print(A,'\n',b)

Enter value of m and n for creating m X n matrix : NOTE m < n


In [455]:
#Define Matrix A:
m=5
n=7
A=[]
for i in range(m):
    MatrixRow=[]
    for j in range(n):
       #print(type(j),i,j,type(i))
       MatrixRow.append(random.randint(0,5))
    A.append(MatrixRow)
    
A

b=[]
for i in range(m):
    b.append(random.randint(0,5))
    
print(A,'\n',b)

[[3, 3, 2, 2, 0, 1, 1], [0, 0, 5, 1, 5, 4, 3], [4, 4, 5, 4, 1, 2, 0], [1, 3, 0, 2, 3, 5, 3], [0, 1, 4, 0, 4, 5, 2]] 
 [5, 3, 5, 5, 1]


In [340]:
AugMatrix=copy.deepcopy(A)
indexOfb=0
i=None
for i in AugMatrix:
    #print(i)
    i.append(b[indexOfb])
    indexOfb+=1
    #AugMatrix.append(i)
AugMatrix

[[2, 4, 6, -3, 4, 8], [4, 8, -3, -3, -2, 1], [0, 0, 2, -7, -6, 4]]

In [339]:
rowSize=len(AugMatrix)
colSize=len(AugMatrix[0])
print(rowSize,colSize)



A=[[2, 4, 6, -3, 4], [4, 8, -3, -3, -2], [0, 0, 2, -7, -6]]
b=[8, 1, 4]

3 6


In [341]:
def swapRow(matrix,i,j):
    matrix[i],matrix[j]=matrix[j],matrix[i]
    return matrix


def checkNonZeroElement(matrix,position):
    print('matrix',matrix)
    nonZeroPos=0
    for i in matrix:
        if i[position] != 0:
            return nonZeroPos
        nonZeroPos+=1
    return -1


def rowOperation(matrix,indexOfR1,indexOfR2,mulFactor):
    newR1=[k*mulFactor for k in matrix[indexOfR1]]
    matrix[indexOfR2]=[x-y for x,y in zip(matrix[indexOfR2],newR1)]
    return matrix
    


def ref(AugMatrix):
    rowSize=len(AugMatrix)
    colSize=len(AugMatrix[0])
    pivot_position,free_variable=[],[]
    print('row_col_size',rowSize,colSize)
    if rowSize == 0 or colSize == 0 :
        sys.exit()
    red=0
    for position in range(colSize):
        for i in range(position,rowSize):
            print('\n\ni,position',i,position)
            i=i+red
            if AugMatrix[i][position]==0 and i+1 < rowSize:
                nonZeroPos=checkNonZeroElement(AugMatrix[i:],position)
                print('i,nonZeroPos',i,nonZeroPos)
                if nonZeroPos >= 0:
                    AugMatrix=swapRow(AugMatrix,i,i+nonZeroPos)
                    pivot_position.append(i-red)
                    for j in range(i+1,rowSize):
                            print('mulFactor swap',i,j,position,AugMatrix[j][position],AugMatrix[i][position])
                            mulFactor=AugMatrix[j][position]/AugMatrix[i][position]
                            indexOfR1=i
                            indexOfR2=j
                            print(AugMatrix,i,j,mulFactor)
                            AugMatrix=rowOperation(AugMatrix,indexOfR1,indexOfR2,mulFactor)
                    break;
                else:
                    free_variable.append(i-red)
                    red=-1
                    break;
            else:
                pivot_position.append(i-red)
                for j in range(i+1,rowSize):
                            print('mulFactor',i,j,position,AugMatrix[j][position],AugMatrix[i][position])
                            mulFactor=AugMatrix[j][position]/AugMatrix[i][position]
                            indexOfR1=i
                            indexOfR2=j
                            print(AugMatrix,i,j,mulFactor)
                            AugMatrix=rowOperation(AugMatrix,indexOfR1,indexOfR2,mulFactor)
                break
        #print('i+1,rowSize',i+1,rowSize)
    print(pivot_position,free_variable)
    return AugMatrix,pivot_position,free_variable

            
ref_AugMatrix,pivot_position,free_variable = ref(AugMatrix)
ref_AugMatrix

row_col_size 3 6


i,position 0 0
mulFactor 0 1 0 4 2
[[2, 4, 6, -3, 4, 8], [4, 8, -3, -3, -2, 1], [0, 0, 2, -7, -6, 4]] 0 1 2.0
mulFactor 0 2 0 0 2
[[2, 4, 6, -3, 4, 8], [0.0, 0.0, -15.0, 3.0, -10.0, -15.0], [0, 0, 2, -7, -6, 4]] 0 2 0.0
i+1,rowSize 1 3


i,position 1 1
matrix [[0.0, 0.0, -15.0, 3.0, -10.0, -15.0], [0.0, 0.0, 2.0, -7.0, -6.0, 4.0]]
i,nonZeroPos 1 -1
i+1,rowSize 2 3


i,position 2 2
mulFactor 1 2 2 2.0 -15.0
[[2, 4, 6, -3, 4, 8], [0.0, 0.0, -15.0, 3.0, -10.0, -15.0], [0.0, 0.0, 2.0, -7.0, -6.0, 4.0]] 1 2 -0.13333333333333333
i+1,rowSize 2 3
i+1,rowSize 2 3
i+1,rowSize 2 3
i+1,rowSize 2 3
[0, 2] [1]


[[2, 4, 6, -3, 4, 8],
 [0.0, 0.0, -15.0, 3.0, -10.0, -15.0],
 [0.0, 0.0, 0.0, -6.6, -7.333333333333333, 2.0]]

In [342]:
ref_AugMatrix
pivot_position
free_variable=[]
for i in range(len(AugMatrix[0])-1):
    if i not in pivot_position:
        free_variable.append(i)
free_variable

[1, 3, 4]

In [351]:
ref_AugMatrix=[[2, 4, 6, -3, 4, 8],
 [0.0, 0.0, -15.0, 3.0, -10.0, -15.0],
 [0.0, 0.0, 0.0, -6.6, -7.333333333333333, 2.0]]

In [352]:
def scalerDivisionOnRow(matrix,indexOfRow,scalerValue):
    newRow=[k/scalerValue for k in matrix[indexOfRow]]
    matrix[indexOfRow]=newRow
    return matrix

    
def checkLastNonZeroPosition(matrix,col_pos):
    row_pos=len(matrix)
    matrix_copy=copy.deepcopy(matrix)
    matrix_copy.reverse()
    for i in range(len(matrix_copy)):
        if matrix_copy[i][col_pos] != 0:
            return row_pos - i -1
    return -1

def rref(ref_AugMatrix):
    rowSize=len(ref_AugMatrix)
    colSize=len(ref_AugMatrix[0])
    
    for j in range(colSize-1):
        if j not in free_variable:
            row_position=checkLastNonZeroPosition(ref_AugMatrix,j)
            print(j,row_position,ref_AugMatrix[row_position][j])
            rref_AugMatrix=scalerDivisionOnRow(ref_AugMatrix,row_position,ref_AugMatrix[row_position][j])
            fixed_row_position=row_position
            row_position=row_position-1
            while row_position >= 0:
                mulFactor=rref_AugMatrix[row_position][j]
                print('mulFactor',rref_AugMatrix,fixed_row_position,row_position,mulFactor)
                rref_AugMatrix=rowOperation(rref_AugMatrix,fixed_row_position,row_position,mulFactor)
                row_position-=1
    return rref_AugMatrix
            
rref_AugMatrix = rref(ref_AugMatrix)         
rref_AugMatrix

0 0 2
2 1 -15.0
mulFactor [[1.0, 2.0, 3.0, -1.5, 2.0, 4.0], [-0.0, -0.0, 1.0, -0.2, 0.6666666666666666, 1.0], [0.0, 0.0, 0.0, -6.6, -7.333333333333333, 2.0]] 1 0 3.0


[[1.0, 2.0, 0.0, -0.8999999999999999, 0.0, 1.0],
 [-0.0, -0.0, 1.0, -0.2, 0.6666666666666666, 1.0],
 [0.0, 0.0, 0.0, -6.6, -7.333333333333333, 2.0]]

In [445]:
rref_AugMatrix
x

[[1.0, 2.0, 3.0, -1.5, 2.0, 4.0],
 [0.0, 0.0, -15.0, 3.0, -10.0, -15.0],
 [0.0, 0.0, 0.0, -6.6, -7.333333333333333, 2.0]]

In [451]:
height=0
pivot_index=[]
for j in range(len(x[0])):
    pivot=False
    for i in range(height,len(x)):
        if x[i][j]!=0:
            pivot=True
            pivot_index.append(j)
            #height-=1
            break
    if not pivot:
        height-=1
    print(i,j,height)
    height+=1

pivot_index

0 0 0
2 1 0
1 2 1
2 3 2
2 4 2
2 5 2


[0, 2, 3]

In [443]:
def extractColFromMatrix(matrix,col_pos):
    col_list=[]
    for i in matrix:
        #print(i,i[col_pos],col_pos)
        temp_list=[]
        temp_list.append(i[col_pos])
        col_list.append(temp_list)
    return col_list

def scalerMultiplicationToColVector(col_matrix,scalerValue):
    for i in range(len(col_matrix)):
        #print(type(col_matrix[i]),type(scalerValue))
        j=[str(k)+'*'+scalerValue for k in col_matrix[i]]
        col_matrix[i]=j
    return col_matrix

def particularSolution(matrix,pivot_position,free_variable):
    col_dict={}
    sol_dict={}
    for col_index in pivot_position:
        col_name='c'+str(col_index)
        col_dict[col_name]=extractColFromMatrix(matrix,col_index)
        #Equating to b
        sol_dict[col_name]=b[col_index]
    print(sol_dict)
    
    sol_equation=[]
    for key in col_dict:
        col_dict[key]=scalerMultiplicationToColVector(col_dict[key],key)
        print(type(col_dict[key]),col_dict[key])

    particular_solution=[]
    for i in range(len(matrix[0])-1):
        temp_list=[]
        if i in pivot_position:
            temp_list.append(sol_dict['c'+str(i)])
        if i in free_variable:
            temp_list.append(0)
        particular_solution.append(temp_list)
    
    return(particular_solution)
        
        
particularSolution=particularSolution(rref_AugMatrix,pivot_position,free_variable) 

def generalSolution(matrix,particularSolution,free_variable):
    # Getting column matrix corresponding to free Variable
    free_variable_columns=[]
    for i in free_variable:
        free_variable_columns.append(extractColFromMatrix(matrix,i))
        #print(free_variable,i,free_variable_columns)
    
    # Writing free variable in terms of pivot column:
    gen_sol_dict={}
    for i in range(len(free_variable_columns)):  
        counter=-1
        for j in free_variable_columns[i]:
            counter+=1
            if j != 0:
                gen_sol_dict['c'+str(i)]=str(j)+'*'+'c'+str(counter)
            counter+=1
    print(gen_sol_dict)
    
generalSolution(rref_AugMatrix,particularSolution,free_variable)

{'c0': 8, 'c2': 4}
<class 'list'> [['1.0*c0'], ['-0.0*c0'], ['0.0*c0']]
<class 'list'> [['0.0*c2'], ['1.0*c2'], ['0.0*c2']]
{'c0': '[0.0]*c2', 'c1': '[-6.6]*c2', 'c2': '[-7.333333333333333]*c2'}


In [391]:
x
c=extractColFromMatrix(x,2)
type(c[0])
c[2][0]

0.0

In [393]:
d=scalerMultiplicationToColVector(c,4)
d

[[12.0], [-60.0], [0.0]]

In [395]:
c

[[12.0], [-60.0], [0.0]]

In [414]:
d={}
d['1']=1
d['2']=2
d


{'1': 1, '2': 2}

In [416]:
d['2']

2

In [436]:
pivot_position
free_variable

[1, 3, 4]

In [432]:
col_dict

NameError: name 'col_dict' is not defined

In [193]:
from numpy import *

def rref(mat,precision=0,GJ=False):
    m,n = mat.shape
    p,t = precision, 1e-1**precision
    A = around(mat.astype(float).copy(),decimals=p )
    if GJ:
        A = hstack((A,identity(n)))
    pcol = -1 #pivot colum
    for i in range(m):
        pcol += 1
        if pcol >= n : break
        #pivot index
        pid = argmax( abs(A[i:,pcol]) )
        #Row exchange
        A[i,:],A[pid+i,:] = A[pid+i,:].copy(),A[i,:].copy()
        #pivot with given precision
        while pcol < n and abs(A[i,pcol]) < t:
            pcol += 1
            if pcol >= n : break
            #pivot index
            pid = argmax( abs(A[i:,pcol]) )
            #Row exchange
            A[i,:],A[pid+i,:] = A[pid+i,:].copy(),A[i,:].copy()
        if pcol >= n : break
        pivot = float(A[i,pcol])
        for j in range(m):
            if j == i: continue
            mul = float(A[j,pcol])/pivot
            A[j,:] = around(A[j,:] - A[i,:]*mul,decimals=p)
        A[i,:] /= pivot
        A[i,:] = around(A[i,:],decimals=p)
        
    if GJ:
        return A[:,:n].copy(),A[:,n:].copy()
    else:
        return A   

array([[ 1.,  0.,  0., -1.,  5.],
       [ 0.,  1.,  0.,  0.,  5.],
       [-0., -0.,  1.,  1., -5.]])

In [468]:
import numpy as np

def qr_decomposition(matrix):
    m, n = matrix.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = matrix[:, j].copy()

        for i in range(j):
            R[i, j] = Q[:, i].dot(matrix[:, j])
            v -= R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Generate a random 5x4 matrix
random_matrix = np.random.rand(5, 4).round(2)

# Perform QR decomposition
Q, R = qr_decomposition(random_matrix)

# Display the results
print("Random Matrix:")
print(random_matrix)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nQ * R:")
print(np.dot(Q, R))

Random Matrix:
[[0.09 0.91 0.17 0.39]
 [0.32 0.2  0.91 0.94]
 [0.7  0.8  0.25 0.1 ]
 [0.08 0.23 0.18 0.44]
 [0.95 0.48 0.81 0.29]]

Matrix Q:
[[ 0.07325552  0.90097585  0.15744429 -0.35490733]
 [ 0.26046406 -0.05389957  0.8662515   0.09283469]
 [ 0.56976513  0.27108323 -0.44672943  0.33585718]
 [ 0.06511601  0.17967804  0.15864921  0.80901032]
 [ 0.77325268 -0.28207628  0.00910336 -0.31324873]]

Matrix R:
[[ 1.22857641  0.96070541  1.02997257  0.5832767 ]
 [ 0.          0.93190403 -0.02425165  0.32507952]
 [ 0.          0.          0.73930262  0.90345238]
 [ 0.          0.          0.          0.24755887]]

Q * R:
[[0.09 0.91 0.17 0.39]
 [0.32 0.2  0.91 0.94]
 [0.7  0.8  0.25 0.1 ]
 [0.08 0.23 0.18 0.44]
 [0.95 0.48 0.81 0.29]]


In [460]:
import numpy as np

def row_echelon_form(matrix):
    m, n = matrix.shape
    A = matrix.copy()

    # Iterate through each row
    for i in range(m):
        # Find the pivot (nonzero) element in the current column
        pivot = A[i, i]

        # Make the pivot element 1
        if pivot != 0:
            A[i, :] /= pivot

            # Eliminate other elements in the current column
            for j in range(i + 1, m):
                factor = A[j, i] / A[i, i]
                A[j, :] -= factor * A[i, :]

    return A

# Example usage:
matrix_to_reduce = np.array([[2, 4, 6, 8], [1, 3, 5, 7], [0, 1, 2, 3]])

# Obtain the row-echelon form
row_echelon_result = row_echelon_form(matrix_to_reduce)

# Display the results
print("Original Matrix:")
print(matrix_to_reduce)
print("\nRow-Echelon Form:")
print(row_echelon_result)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'